// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SharpScape.Api.Data;

#nullable disable

namespace SharpScape.Api.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20220702022543_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("SharpScape.Api.Models.ForumCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ForumCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Talk about sports, entertainment, music, movies, your favorite color, talk about enything.",
                            Name = "General Discussion"
                        },
                        new
                        {
                            Id = 2,
                            Description = "New to the community? Please stop by, say hi and tell us a bit about yourself.",
                            Name = "Introductions"
                        },
                        new
                        {
                            Id = 3,
                            Description = "This forum features announcements from the community staff. If there is a new post in this forum, please check it out.",
                            Name = "Announcements"
                        },
                        new
                        {
                            Id = 4,
                            Description = "This forum is for private, staff member only discussions, usually pertaining to the community itself.",
                            Name = "Staff Discussion"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Various versions have evolved over the years, sometimes by accident, sometimes on purpose passage of Lorem Ipsum (injected humour and the like).",
                            Name = "Lorem Ipsum is simply dummy text"
                        },
                        new
                        {
                            Id = 6,
                            Description = "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
                            Name = "There are many variations of passages"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
                            Name = "The standard chunk of Lorem Ipsum"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Internet tend to repeat predefined chunks as necessary, making this the.",
                            Name = "Lorem Ipsum, you need to be sure there"
                        });
                });

            modelBuilder.Entity("SharpScape.Api.Models.ForumPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("ThreadId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ThreadId");

                    b.ToTable("ForumPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(5806),
                            ThreadId = 1
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(5818),
                            ThreadId = 2
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(5824),
                            ThreadId = 3
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(5829),
                            ThreadId = 4
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(5834),
                            ThreadId = 5
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(5841),
                            ThreadId = 6
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(5847),
                            ThreadId = 7
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(5852),
                            ThreadId = 8
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(5857),
                            ThreadId = 9
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(5864),
                            ThreadId = 10
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(5869),
                            ThreadId = 11
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(5875),
                            ThreadId = 12
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(5880),
                            ThreadId = 13
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(5885),
                            ThreadId = 14
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(5891),
                            ThreadId = 15
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(5896),
                            ThreadId = 16
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(5901),
                            ThreadId = 17
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(5908),
                            ThreadId = 18
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(5913),
                            ThreadId = 19
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(5919),
                            ThreadId = 20
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(5924),
                            ThreadId = 21
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(5929),
                            ThreadId = 22
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(5935),
                            ThreadId = 23
                        },
                        new
                        {
                            Id = 24,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(5940),
                            ThreadId = 24
                        },
                        new
                        {
                            Id = 25,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(5945),
                            ThreadId = 25
                        },
                        new
                        {
                            Id = 26,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(5950),
                            ThreadId = 26
                        },
                        new
                        {
                            Id = 27,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(5956),
                            ThreadId = 27
                        },
                        new
                        {
                            Id = 28,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(5961),
                            ThreadId = 28
                        },
                        new
                        {
                            Id = 29,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(6004),
                            ThreadId = 29
                        },
                        new
                        {
                            Id = 30,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(6010),
                            ThreadId = 30
                        },
                        new
                        {
                            Id = 31,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(6015),
                            ThreadId = 31
                        },
                        new
                        {
                            Id = 32,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(6021),
                            ThreadId = 32
                        },
                        new
                        {
                            Id = 33,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(6026),
                            ThreadId = 33
                        },
                        new
                        {
                            Id = 34,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(6033),
                            ThreadId = 34
                        },
                        new
                        {
                            Id = 35,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(6039),
                            ThreadId = 35
                        },
                        new
                        {
                            Id = 36,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(6044),
                            ThreadId = 36
                        },
                        new
                        {
                            Id = 37,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(6049),
                            ThreadId = 37
                        },
                        new
                        {
                            Id = 38,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(6054),
                            ThreadId = 38
                        },
                        new
                        {
                            Id = 39,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(6060),
                            ThreadId = 39
                        },
                        new
                        {
                            Id = 40,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(6065),
                            ThreadId = 40
                        },
                        new
                        {
                            Id = 41,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(6070),
                            ThreadId = 41
                        },
                        new
                        {
                            Id = 42,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(6076),
                            ThreadId = 42
                        },
                        new
                        {
                            Id = 43,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(6081),
                            ThreadId = 43
                        },
                        new
                        {
                            Id = 44,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(6086),
                            ThreadId = 44
                        },
                        new
                        {
                            Id = 45,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(6092),
                            ThreadId = 45
                        },
                        new
                        {
                            Id = 46,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(6097),
                            ThreadId = 46
                        },
                        new
                        {
                            Id = 47,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(6103),
                            ThreadId = 47
                        },
                        new
                        {
                            Id = 48,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(6108),
                            ThreadId = 48
                        },
                        new
                        {
                            Id = 49,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(6113),
                            ThreadId = 49
                        },
                        new
                        {
                            Id = 50,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(6119),
                            ThreadId = 50
                        },
                        new
                        {
                            Id = 51,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(6124),
                            ThreadId = 51
                        },
                        new
                        {
                            Id = 52,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(6129),
                            ThreadId = 52
                        },
                        new
                        {
                            Id = 53,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(6135),
                            ThreadId = 53
                        },
                        new
                        {
                            Id = 54,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(6140),
                            ThreadId = 54
                        },
                        new
                        {
                            Id = 55,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(6145),
                            ThreadId = 55
                        },
                        new
                        {
                            Id = 56,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(6151),
                            ThreadId = 56
                        },
                        new
                        {
                            Id = 57,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(6156),
                            ThreadId = 57
                        },
                        new
                        {
                            Id = 58,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(6161),
                            ThreadId = 58
                        },
                        new
                        {
                            Id = 59,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(6167),
                            ThreadId = 59
                        },
                        new
                        {
                            Id = 60,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(6172),
                            ThreadId = 60
                        },
                        new
                        {
                            Id = 61,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(6177),
                            ThreadId = 61
                        },
                        new
                        {
                            Id = 62,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(6183),
                            ThreadId = 62
                        },
                        new
                        {
                            Id = 63,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(6188),
                            ThreadId = 63
                        },
                        new
                        {
                            Id = 64,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(6193),
                            ThreadId = 64
                        });
                });

            modelBuilder.Entity("SharpScape.Api.Models.ForumThread", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("Replies")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Views")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Votes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("ForumThreads");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
                            CategoryId = 1,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5012),
                            Replies = 0,
                            Title = "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 2,
                            Body = "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
                            CategoryId = 1,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5079),
                            Replies = 0,
                            Title = "qui est esse",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 3,
                            Body = "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
                            CategoryId = 1,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5100),
                            Replies = 0,
                            Title = "ea molestias quasi exercitationem repellat qui ipsa sit aut",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 4,
                            Body = "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
                            CategoryId = 1,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5110),
                            Replies = 0,
                            Title = "eum et est occaecati",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 5,
                            Body = "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
                            CategoryId = 1,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5121),
                            Replies = 0,
                            Title = "nesciunt quas odio",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 6,
                            Body = "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
                            CategoryId = 1,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5131),
                            Replies = 0,
                            Title = "dolorem eum magni eos aperiam quia",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 7,
                            Body = "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
                            CategoryId = 1,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5141),
                            Replies = 0,
                            Title = "magnam facilis autem",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 8,
                            Body = "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
                            CategoryId = 1,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5152),
                            Replies = 0,
                            Title = "dolorem dolore est ipsam",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 9,
                            Body = "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
                            CategoryId = 2,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5229),
                            Replies = 0,
                            Title = "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 10,
                            Body = "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
                            CategoryId = 2,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5238),
                            Replies = 0,
                            Title = "qui est esse",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 11,
                            Body = "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
                            CategoryId = 2,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5248),
                            Replies = 0,
                            Title = "ea molestias quasi exercitationem repellat qui ipsa sit aut",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 12,
                            Body = "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
                            CategoryId = 2,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5259),
                            Replies = 0,
                            Title = "eum et est occaecati",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 13,
                            Body = "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
                            CategoryId = 2,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5268),
                            Replies = 0,
                            Title = "nesciunt quas odio",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 14,
                            Body = "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
                            CategoryId = 2,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5277),
                            Replies = 0,
                            Title = "dolorem eum magni eos aperiam quia",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 15,
                            Body = "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
                            CategoryId = 2,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5286),
                            Replies = 0,
                            Title = "magnam facilis autem",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 16,
                            Body = "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
                            CategoryId = 2,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5295),
                            Replies = 0,
                            Title = "dolorem dolore est ipsam",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 17,
                            Body = "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
                            CategoryId = 3,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5304),
                            Replies = 0,
                            Title = "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 18,
                            Body = "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
                            CategoryId = 3,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5314),
                            Replies = 0,
                            Title = "qui est esse",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 19,
                            Body = "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
                            CategoryId = 3,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5323),
                            Replies = 0,
                            Title = "ea molestias quasi exercitationem repellat qui ipsa sit aut",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 20,
                            Body = "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
                            CategoryId = 3,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5349),
                            Replies = 0,
                            Title = "eum et est occaecati",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 21,
                            Body = "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
                            CategoryId = 3,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5362),
                            Replies = 0,
                            Title = "nesciunt quas odio",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 22,
                            Body = "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
                            CategoryId = 3,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5373),
                            Replies = 0,
                            Title = "dolorem eum magni eos aperiam quia",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 23,
                            Body = "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
                            CategoryId = 3,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5383),
                            Replies = 0,
                            Title = "magnam facilis autem",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 24,
                            Body = "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
                            CategoryId = 3,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5393),
                            Replies = 0,
                            Title = "dolorem dolore est ipsam",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 25,
                            Body = "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
                            CategoryId = 3,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5404),
                            Replies = 0,
                            Title = "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 26,
                            Body = "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
                            CategoryId = 3,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5413),
                            Replies = 0,
                            Title = "qui est esse",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 27,
                            Body = "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
                            CategoryId = 3,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5422),
                            Replies = 0,
                            Title = "ea molestias quasi exercitationem repellat qui ipsa sit aut",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 28,
                            Body = "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
                            CategoryId = 3,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5430),
                            Replies = 0,
                            Title = "eum et est occaecati",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 29,
                            Body = "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
                            CategoryId = 3,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5439),
                            Replies = 0,
                            Title = "nesciunt quas odio",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 30,
                            Body = "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
                            CategoryId = 3,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5447),
                            Replies = 0,
                            Title = "dolorem eum magni eos aperiam quia",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 31,
                            Body = "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
                            CategoryId = 3,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5455),
                            Replies = 0,
                            Title = "magnam facilis autem",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 32,
                            Body = "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
                            CategoryId = 3,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5464),
                            Replies = 0,
                            Title = "dolorem dolore est ipsam",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 33,
                            Body = "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
                            CategoryId = 5,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5472),
                            Replies = 0,
                            Title = "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 34,
                            Body = "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
                            CategoryId = 5,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5481),
                            Replies = 0,
                            Title = "qui est esse",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 35,
                            Body = "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
                            CategoryId = 5,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5489),
                            Replies = 0,
                            Title = "ea molestias quasi exercitationem repellat qui ipsa sit aut",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 36,
                            Body = "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
                            CategoryId = 5,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5498),
                            Replies = 0,
                            Title = "eum et est occaecati",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 37,
                            Body = "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
                            CategoryId = 5,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5506),
                            Replies = 0,
                            Title = "nesciunt quas odio",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 38,
                            Body = "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
                            CategoryId = 5,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5515),
                            Replies = 0,
                            Title = "dolorem eum magni eos aperiam quia",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 39,
                            Body = "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
                            CategoryId = 5,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5523),
                            Replies = 0,
                            Title = "magnam facilis autem",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 40,
                            Body = "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
                            CategoryId = 5,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5531),
                            Replies = 0,
                            Title = "dolorem dolore est ipsam",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 41,
                            Body = "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
                            CategoryId = 6,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5540),
                            Replies = 0,
                            Title = "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 42,
                            Body = "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
                            CategoryId = 6,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5548),
                            Replies = 0,
                            Title = "qui est esse",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 43,
                            Body = "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
                            CategoryId = 6,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5556),
                            Replies = 0,
                            Title = "ea molestias quasi exercitationem repellat qui ipsa sit aut",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 44,
                            Body = "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
                            CategoryId = 6,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5565),
                            Replies = 0,
                            Title = "eum et est occaecati",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 45,
                            Body = "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
                            CategoryId = 6,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5573),
                            Replies = 0,
                            Title = "nesciunt quas odio",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 46,
                            Body = "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
                            CategoryId = 6,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5582),
                            Replies = 0,
                            Title = "dolorem eum magni eos aperiam quia",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 47,
                            Body = "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
                            CategoryId = 6,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5590),
                            Replies = 0,
                            Title = "magnam facilis autem",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 48,
                            Body = "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
                            CategoryId = 6,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5598),
                            Replies = 0,
                            Title = "dolorem dolore est ipsam",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 49,
                            Body = "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
                            CategoryId = 7,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5607),
                            Replies = 0,
                            Title = "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 50,
                            Body = "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
                            CategoryId = 7,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5615),
                            Replies = 0,
                            Title = "qui est esse",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 51,
                            Body = "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
                            CategoryId = 7,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5624),
                            Replies = 0,
                            Title = "ea molestias quasi exercitationem repellat qui ipsa sit aut",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 52,
                            Body = "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
                            CategoryId = 7,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5632),
                            Replies = 0,
                            Title = "eum et est occaecati",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 53,
                            Body = "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
                            CategoryId = 7,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5641),
                            Replies = 0,
                            Title = "nesciunt quas odio",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 54,
                            Body = "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
                            CategoryId = 7,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5649),
                            Replies = 0,
                            Title = "dolorem eum magni eos aperiam quia",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 55,
                            Body = "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
                            CategoryId = 7,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5658),
                            Replies = 0,
                            Title = "magnam facilis autem",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 56,
                            Body = "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
                            CategoryId = 7,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5666),
                            Replies = 0,
                            Title = "dolorem dolore est ipsam",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 57,
                            Body = "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
                            CategoryId = 8,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5674),
                            Replies = 0,
                            Title = "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 58,
                            Body = "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
                            CategoryId = 8,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5683),
                            Replies = 0,
                            Title = "qui est esse",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 59,
                            Body = "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
                            CategoryId = 8,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5691),
                            Replies = 0,
                            Title = "ea molestias quasi exercitationem repellat qui ipsa sit aut",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 60,
                            Body = "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
                            CategoryId = 8,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5700),
                            Replies = 0,
                            Title = "eum et est occaecati",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 61,
                            Body = "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
                            CategoryId = 8,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5708),
                            Replies = 0,
                            Title = "nesciunt quas odio",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 62,
                            Body = "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
                            CategoryId = 8,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5717),
                            Replies = 0,
                            Title = "dolorem eum magni eos aperiam quia",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 63,
                            Body = "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
                            CategoryId = 8,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5725),
                            Replies = 0,
                            Title = "magnam facilis autem",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 64,
                            Body = "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
                            CategoryId = 8,
                            Created = new DateTime(2022, 7, 1, 19, 25, 42, 776, DateTimeKind.Local).AddTicks(5734),
                            Replies = 0,
                            Title = "dolorem dolore est ipsam",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        });
                });

            modelBuilder.Entity("SharpScape.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(4216),
                            Email = "admin@sharpscape.net",
                            PasswordHash = new byte[] { 156, 172, 177, 44, 60, 11, 22, 184, 154, 251, 9, 216, 139, 106, 108, 16, 139, 114, 142, 224, 89, 197, 54, 205, 184, 148, 67, 143, 30, 120, 175, 147, 130, 222, 199, 89, 109, 108, 72, 21, 7, 58, 44, 233, 111, 129, 222, 25, 117, 240, 68, 120, 40, 178, 233, 74, 58, 4, 55, 255, 75, 194, 225, 161 },
                            PasswordSalt = new byte[] { 245, 108, 46, 58, 222, 8, 237, 223, 104, 160, 192, 73, 227, 128, 199, 83, 246, 81, 111, 158, 130, 9, 1, 241, 27, 231, 232, 63, 153, 10, 147, 187, 228, 50, 14, 36, 55, 2, 46, 112, 187, 47, 6, 100, 19, 156, 77, 3, 0, 180, 203, 79, 114, 62, 178, 203, 30, 139, 214, 123, 230, 109, 2, 249, 188, 61, 19, 245, 56, 209, 166, 140, 151, 216, 186, 207, 28, 161, 119, 115, 224, 190, 204, 7, 217, 48, 44, 205, 162, 146, 189, 90, 195, 94, 24, 188, 131, 11, 173, 103, 95, 127, 194, 150, 186, 15, 151, 44, 81, 20, 174, 100, 178, 179, 176, 29, 84, 23, 126, 103, 198, 24, 168, 198, 176, 155, 0, 173 },
                            Role = "User",
                            Username = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(4614),
                            Email = "pringle@example.com",
                            PasswordHash = new byte[] { 114, 29, 106, 210, 63, 167, 105, 70, 28, 12, 222, 88, 137, 142, 228, 101, 37, 170, 23, 202, 134, 88, 138, 234, 82, 0, 203, 238, 136, 136, 175, 227, 192, 30, 222, 243, 38, 59, 77, 152, 199, 52, 120, 23, 2, 159, 108, 216, 20, 93, 204, 97, 70, 44, 140, 252, 239, 28, 138, 14, 87, 175, 216, 93 },
                            PasswordSalt = new byte[] { 191, 124, 45, 251, 52, 24, 175, 110, 129, 205, 111, 123, 180, 101, 73, 210, 46, 168, 160, 70, 7, 108, 218, 148, 83, 105, 183, 137, 93, 92, 55, 157, 212, 102, 216, 237, 164, 93, 210, 224, 196, 81, 190, 163, 220, 231, 49, 226, 2, 199, 149, 66, 55, 110, 91, 119, 205, 39, 66, 233, 153, 227, 132, 101, 245, 64, 48, 0, 164, 251, 236, 80, 244, 245, 107, 146, 207, 217, 97, 49, 7, 57, 134, 131, 78, 30, 234, 235, 141, 165, 236, 108, 66, 144, 86, 40, 249, 250, 148, 79, 227, 95, 111, 125, 158, 135, 37, 108, 122, 36, 152, 187, 206, 83, 217, 58, 45, 109, 54, 47, 193, 151, 36, 36, 137, 61, 93, 180 },
                            Role = "User",
                            Username = "Pringleton"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2022, 7, 2, 2, 25, 42, 776, DateTimeKind.Utc).AddTicks(4663),
                            Email = "john@dot.net",
                            PasswordHash = new byte[] { 39, 251, 34, 40, 198, 234, 123, 10, 253, 203, 230, 246, 17, 228, 180, 54, 194, 188, 160, 161, 88, 58, 40, 66, 105, 56, 107, 251, 61, 8, 91, 205, 92, 226, 13, 238, 240, 91, 155, 214, 168, 132, 153, 213, 61, 119, 175, 248, 154, 130, 46, 233, 137, 153, 239, 186, 75, 61, 232, 242, 180, 35, 122, 186 },
                            PasswordSalt = new byte[] { 175, 101, 183, 210, 31, 162, 230, 104, 109, 89, 187, 47, 203, 185, 206, 26, 240, 102, 139, 75, 215, 237, 171, 223, 144, 94, 211, 83, 126, 174, 97, 118, 45, 114, 151, 34, 255, 198, 92, 126, 64, 46, 9, 153, 99, 13, 43, 82, 174, 172, 6, 17, 171, 102, 187, 247, 110, 91, 186, 141, 243, 50, 40, 29, 16, 191, 131, 225, 128, 158, 57, 134, 142, 151, 192, 151, 237, 72, 237, 73, 46, 110, 3, 183, 9, 135, 89, 218, 38, 194, 89, 153, 196, 231, 62, 226, 254, 251, 138, 185, 2, 139, 204, 227, 120, 252, 127, 47, 12, 115, 38, 30, 185, 82, 174, 29, 160, 86, 43, 207, 173, 193, 103, 209, 255, 68, 77, 212 },
                            Role = "User",
                            Username = "John Dotnet"
                        });
                });

            modelBuilder.Entity("SharpScape.Api.Models.ForumPost", b =>
                {
                    b.HasOne("SharpScape.Api.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharpScape.Api.Models.ForumThread", "ForumThread")
                        .WithMany()
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("ForumThread");
                });

            modelBuilder.Entity("SharpScape.Api.Models.ForumThread", b =>
                {
                    b.HasOne("SharpScape.Api.Models.ForumCategory", "ForumCategory")
                        .WithMany("Threads")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharpScape.Api.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("ForumCategory");
                });

            modelBuilder.Entity("SharpScape.Api.Models.ForumCategory", b =>
                {
                    b.Navigation("Threads");
                });
#pragma warning restore 612, 618
        }
    }
}
