// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SharpScape.Api.Data;

#nullable disable

namespace SharpScape.Api.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20220705212054_UserRefreshToken")]
    partial class UserRefreshToken
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("SharpScape.Api.Models.ForumCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ForumCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Talk about sports, entertainment, music, movies, your favorite color, talk about enything.",
                            Name = "General Discussion"
                        },
                        new
                        {
                            Id = 2,
                            Description = "New to the community? Please stop by, say hi and tell us a bit about yourself.",
                            Name = "Introductions"
                        },
                        new
                        {
                            Id = 3,
                            Description = "This forum features announcements from the community staff. If there is a new post in this forum, please check it out.",
                            Name = "Announcements"
                        },
                        new
                        {
                            Id = 4,
                            Description = "This forum is for private, staff member only discussions, usually pertaining to the community itself.",
                            Name = "Staff Discussion"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Various versions have evolved over the years, sometimes by accident, sometimes on purpose passage of Lorem Ipsum (injected humour and the like).",
                            Name = "Lorem Ipsum is simply dummy text"
                        },
                        new
                        {
                            Id = 6,
                            Description = "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
                            Name = "There are many variations of passages"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
                            Name = "The standard chunk of Lorem Ipsum"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Internet tend to repeat predefined chunks as necessary, making this the.",
                            Name = "Lorem Ipsum, you need to be sure there"
                        });
                });

            modelBuilder.Entity("SharpScape.Api.Models.ForumPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("ThreadId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ThreadId");

                    b.ToTable("ForumPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1302),
                            ThreadId = 2
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1310),
                            ThreadId = 3
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1315),
                            ThreadId = 4
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1318),
                            ThreadId = 5
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1322),
                            ThreadId = 6
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1327),
                            ThreadId = 7
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1331),
                            ThreadId = 8
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1334),
                            ThreadId = 1
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1338),
                            ThreadId = 2
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1343),
                            ThreadId = 3
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1347),
                            ThreadId = 4
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1350),
                            ThreadId = 5
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1354),
                            ThreadId = 6
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1357),
                            ThreadId = 7
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1361),
                            ThreadId = 8
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1364),
                            ThreadId = 1
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1368),
                            ThreadId = 2
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1372),
                            ThreadId = 3
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1376),
                            ThreadId = 4
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1380),
                            ThreadId = 5
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1383),
                            ThreadId = 6
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1387),
                            ThreadId = 7
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1390),
                            ThreadId = 8
                        },
                        new
                        {
                            Id = 24,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1394),
                            ThreadId = 1
                        },
                        new
                        {
                            Id = 25,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1397),
                            ThreadId = 2
                        },
                        new
                        {
                            Id = 26,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1401),
                            ThreadId = 3
                        },
                        new
                        {
                            Id = 27,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1404),
                            ThreadId = 4
                        },
                        new
                        {
                            Id = 28,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1408),
                            ThreadId = 5
                        },
                        new
                        {
                            Id = 29,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1411),
                            ThreadId = 6
                        },
                        new
                        {
                            Id = 30,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1415),
                            ThreadId = 7
                        },
                        new
                        {
                            Id = 31,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1418),
                            ThreadId = 8
                        },
                        new
                        {
                            Id = 32,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1422),
                            ThreadId = 1
                        },
                        new
                        {
                            Id = 33,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1425),
                            ThreadId = 2
                        },
                        new
                        {
                            Id = 34,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1430),
                            ThreadId = 3
                        },
                        new
                        {
                            Id = 35,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1434),
                            ThreadId = 4
                        },
                        new
                        {
                            Id = 36,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1437),
                            ThreadId = 5
                        },
                        new
                        {
                            Id = 37,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1441),
                            ThreadId = 6
                        },
                        new
                        {
                            Id = 38,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1444),
                            ThreadId = 7
                        },
                        new
                        {
                            Id = 39,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1448),
                            ThreadId = 8
                        },
                        new
                        {
                            Id = 40,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1451),
                            ThreadId = 1
                        },
                        new
                        {
                            Id = 41,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1454),
                            ThreadId = 2
                        },
                        new
                        {
                            Id = 42,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1458),
                            ThreadId = 3
                        },
                        new
                        {
                            Id = 43,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1462),
                            ThreadId = 4
                        },
                        new
                        {
                            Id = 44,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1465),
                            ThreadId = 5
                        },
                        new
                        {
                            Id = 45,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1528),
                            ThreadId = 6
                        },
                        new
                        {
                            Id = 46,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1533),
                            ThreadId = 7
                        },
                        new
                        {
                            Id = 47,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1537),
                            ThreadId = 8
                        },
                        new
                        {
                            Id = 48,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1540),
                            ThreadId = 1
                        },
                        new
                        {
                            Id = 49,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1544),
                            ThreadId = 2
                        },
                        new
                        {
                            Id = 50,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1547),
                            ThreadId = 3
                        },
                        new
                        {
                            Id = 51,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1551),
                            ThreadId = 4
                        },
                        new
                        {
                            Id = 52,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1554),
                            ThreadId = 5
                        },
                        new
                        {
                            Id = 53,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1558),
                            ThreadId = 6
                        },
                        new
                        {
                            Id = 54,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1561),
                            ThreadId = 7
                        },
                        new
                        {
                            Id = 55,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1565),
                            ThreadId = 8
                        },
                        new
                        {
                            Id = 56,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1568),
                            ThreadId = 1
                        },
                        new
                        {
                            Id = 57,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1572),
                            ThreadId = 2
                        },
                        new
                        {
                            Id = 58,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1575),
                            ThreadId = 3
                        },
                        new
                        {
                            Id = 59,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1579),
                            ThreadId = 4
                        },
                        new
                        {
                            Id = 60,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1582),
                            ThreadId = 5
                        },
                        new
                        {
                            Id = 61,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1586),
                            ThreadId = 6
                        },
                        new
                        {
                            Id = 62,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1589),
                            ThreadId = 7
                        },
                        new
                        {
                            Id = 63,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1593),
                            ThreadId = 8
                        },
                        new
                        {
                            Id = 64,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(1596),
                            ThreadId = 1
                        });
                });

            modelBuilder.Entity("SharpScape.Api.Models.ForumThread", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("Replies")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Views")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Votes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("ForumThreads");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
                            CategoryId = 1,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(878),
                            Replies = 0,
                            Title = "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 2,
                            Body = "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
                            CategoryId = 1,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(884),
                            Replies = 0,
                            Title = "qui est esse",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 3,
                            Body = "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
                            CategoryId = 1,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(890),
                            Replies = 0,
                            Title = "ea molestias quasi exercitationem repellat qui ipsa sit aut",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 4,
                            Body = "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
                            CategoryId = 1,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(896),
                            Replies = 0,
                            Title = "eum et est occaecati",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 5,
                            Body = "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
                            CategoryId = 1,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(901),
                            Replies = 0,
                            Title = "nesciunt quas odio",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 6,
                            Body = "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
                            CategoryId = 1,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(906),
                            Replies = 0,
                            Title = "dolorem eum magni eos aperiam quia",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 7,
                            Body = "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
                            CategoryId = 1,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(912),
                            Replies = 0,
                            Title = "magnam facilis autem",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 8,
                            Body = "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
                            CategoryId = 1,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(917),
                            Replies = 0,
                            Title = "dolorem dolore est ipsam",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 9,
                            Body = "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
                            CategoryId = 2,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(923),
                            Replies = 0,
                            Title = "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 10,
                            Body = "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
                            CategoryId = 2,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(928),
                            Replies = 0,
                            Title = "qui est esse",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 11,
                            Body = "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
                            CategoryId = 2,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(934),
                            Replies = 0,
                            Title = "ea molestias quasi exercitationem repellat qui ipsa sit aut",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 12,
                            Body = "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
                            CategoryId = 2,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(939),
                            Replies = 0,
                            Title = "eum et est occaecati",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 13,
                            Body = "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
                            CategoryId = 2,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(944),
                            Replies = 0,
                            Title = "nesciunt quas odio",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 14,
                            Body = "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
                            CategoryId = 2,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(950),
                            Replies = 0,
                            Title = "dolorem eum magni eos aperiam quia",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 15,
                            Body = "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
                            CategoryId = 2,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(955),
                            Replies = 0,
                            Title = "magnam facilis autem",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 16,
                            Body = "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
                            CategoryId = 2,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(961),
                            Replies = 0,
                            Title = "dolorem dolore est ipsam",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 17,
                            Body = "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
                            CategoryId = 3,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(966),
                            Replies = 0,
                            Title = "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 18,
                            Body = "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
                            CategoryId = 3,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(971),
                            Replies = 0,
                            Title = "qui est esse",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 19,
                            Body = "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
                            CategoryId = 3,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(977),
                            Replies = 0,
                            Title = "ea molestias quasi exercitationem repellat qui ipsa sit aut",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 20,
                            Body = "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
                            CategoryId = 3,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(982),
                            Replies = 0,
                            Title = "eum et est occaecati",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 21,
                            Body = "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
                            CategoryId = 3,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(987),
                            Replies = 0,
                            Title = "nesciunt quas odio",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 22,
                            Body = "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
                            CategoryId = 3,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(993),
                            Replies = 0,
                            Title = "dolorem eum magni eos aperiam quia",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 23,
                            Body = "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
                            CategoryId = 3,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(998),
                            Replies = 0,
                            Title = "magnam facilis autem",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 24,
                            Body = "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
                            CategoryId = 3,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1004),
                            Replies = 0,
                            Title = "dolorem dolore est ipsam",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 25,
                            Body = "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
                            CategoryId = 3,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1009),
                            Replies = 0,
                            Title = "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 26,
                            Body = "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
                            CategoryId = 3,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1014),
                            Replies = 0,
                            Title = "qui est esse",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 27,
                            Body = "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
                            CategoryId = 3,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1020),
                            Replies = 0,
                            Title = "ea molestias quasi exercitationem repellat qui ipsa sit aut",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 28,
                            Body = "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
                            CategoryId = 3,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1025),
                            Replies = 0,
                            Title = "eum et est occaecati",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 29,
                            Body = "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
                            CategoryId = 3,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1073),
                            Replies = 0,
                            Title = "nesciunt quas odio",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 30,
                            Body = "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
                            CategoryId = 3,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1079),
                            Replies = 0,
                            Title = "dolorem eum magni eos aperiam quia",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 31,
                            Body = "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
                            CategoryId = 3,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1084),
                            Replies = 0,
                            Title = "magnam facilis autem",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 32,
                            Body = "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
                            CategoryId = 3,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1090),
                            Replies = 0,
                            Title = "dolorem dolore est ipsam",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 33,
                            Body = "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
                            CategoryId = 5,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1096),
                            Replies = 0,
                            Title = "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 34,
                            Body = "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
                            CategoryId = 5,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1101),
                            Replies = 0,
                            Title = "qui est esse",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 35,
                            Body = "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
                            CategoryId = 5,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1106),
                            Replies = 0,
                            Title = "ea molestias quasi exercitationem repellat qui ipsa sit aut",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 36,
                            Body = "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
                            CategoryId = 5,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1111),
                            Replies = 0,
                            Title = "eum et est occaecati",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 37,
                            Body = "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
                            CategoryId = 5,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1117),
                            Replies = 0,
                            Title = "nesciunt quas odio",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 38,
                            Body = "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
                            CategoryId = 5,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1122),
                            Replies = 0,
                            Title = "dolorem eum magni eos aperiam quia",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 39,
                            Body = "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
                            CategoryId = 5,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1128),
                            Replies = 0,
                            Title = "magnam facilis autem",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 40,
                            Body = "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
                            CategoryId = 5,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1133),
                            Replies = 0,
                            Title = "dolorem dolore est ipsam",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 41,
                            Body = "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
                            CategoryId = 6,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1138),
                            Replies = 0,
                            Title = "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 42,
                            Body = "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
                            CategoryId = 6,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1143),
                            Replies = 0,
                            Title = "qui est esse",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 43,
                            Body = "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
                            CategoryId = 6,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1149),
                            Replies = 0,
                            Title = "ea molestias quasi exercitationem repellat qui ipsa sit aut",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 44,
                            Body = "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
                            CategoryId = 6,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1154),
                            Replies = 0,
                            Title = "eum et est occaecati",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 45,
                            Body = "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
                            CategoryId = 6,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1160),
                            Replies = 0,
                            Title = "nesciunt quas odio",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 46,
                            Body = "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
                            CategoryId = 6,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1165),
                            Replies = 0,
                            Title = "dolorem eum magni eos aperiam quia",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 47,
                            Body = "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
                            CategoryId = 6,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1170),
                            Replies = 0,
                            Title = "magnam facilis autem",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 48,
                            Body = "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
                            CategoryId = 6,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1176),
                            Replies = 0,
                            Title = "dolorem dolore est ipsam",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 49,
                            Body = "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
                            CategoryId = 7,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1181),
                            Replies = 0,
                            Title = "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 50,
                            Body = "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
                            CategoryId = 7,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1187),
                            Replies = 0,
                            Title = "qui est esse",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 51,
                            Body = "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
                            CategoryId = 7,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1192),
                            Replies = 0,
                            Title = "ea molestias quasi exercitationem repellat qui ipsa sit aut",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 52,
                            Body = "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
                            CategoryId = 7,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1197),
                            Replies = 0,
                            Title = "eum et est occaecati",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 53,
                            Body = "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
                            CategoryId = 7,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1203),
                            Replies = 0,
                            Title = "nesciunt quas odio",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 54,
                            Body = "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
                            CategoryId = 7,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1208),
                            Replies = 0,
                            Title = "dolorem eum magni eos aperiam quia",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 55,
                            Body = "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
                            CategoryId = 7,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1213),
                            Replies = 0,
                            Title = "magnam facilis autem",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 56,
                            Body = "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
                            CategoryId = 7,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1219),
                            Replies = 0,
                            Title = "dolorem dolore est ipsam",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 57,
                            Body = "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
                            CategoryId = 8,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1224),
                            Replies = 0,
                            Title = "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 58,
                            Body = "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
                            CategoryId = 8,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1229),
                            Replies = 0,
                            Title = "qui est esse",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 59,
                            Body = "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
                            CategoryId = 8,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1235),
                            Replies = 0,
                            Title = "ea molestias quasi exercitationem repellat qui ipsa sit aut",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 60,
                            Body = "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
                            CategoryId = 8,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1240),
                            Replies = 0,
                            Title = "eum et est occaecati",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 61,
                            Body = "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
                            CategoryId = 8,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1245),
                            Replies = 0,
                            Title = "nesciunt quas odio",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 62,
                            Body = "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
                            CategoryId = 8,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1251),
                            Replies = 0,
                            Title = "dolorem eum magni eos aperiam quia",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 63,
                            Body = "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
                            CategoryId = 8,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1256),
                            Replies = 0,
                            Title = "magnam facilis autem",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 64,
                            Body = "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
                            CategoryId = 8,
                            Created = new DateTime(2022, 7, 5, 15, 20, 54, 484, DateTimeKind.Local).AddTicks(1262),
                            Replies = 0,
                            Title = "dolorem dolore est ipsam",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        });
                });

            modelBuilder.Entity("SharpScape.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(280),
                            Email = "admin@sharpscape.net",
                            PasswordHash = new byte[] { 27, 123, 141, 204, 241, 156, 166, 162, 151, 148, 177, 214, 140, 129, 105, 19, 35, 252, 187, 186, 73, 19, 207, 13, 150, 185, 103, 200, 6, 200, 230, 100, 252, 170, 248, 192, 42, 108, 6, 229, 208, 117, 116, 37, 92, 233, 8, 116, 109, 159, 133, 192, 17, 254, 138, 36, 252, 30, 75, 55, 105, 19, 205, 210 },
                            PasswordSalt = new byte[] { 222, 199, 162, 228, 60, 177, 50, 192, 37, 58, 189, 187, 242, 124, 50, 65, 94, 155, 25, 71, 37, 107, 46, 141, 133, 162, 78, 34, 97, 210, 57, 114, 51, 117, 212, 136, 19, 66, 101, 24, 249, 154, 18, 45, 167, 97, 81, 59, 120, 228, 8, 234, 174, 117, 194, 63, 67, 22, 190, 167, 48, 226, 51, 29, 132, 106, 145, 53, 51, 239, 206, 206, 151, 189, 77, 174, 70, 36, 52, 118, 15, 231, 92, 251, 170, 102, 27, 123, 86, 101, 219, 145, 188, 45, 146, 60, 88, 50, 191, 77, 245, 81, 244, 210, 82, 49, 60, 183, 54, 58, 17, 134, 187, 177, 140, 146, 118, 187, 221, 211, 197, 106, 75, 216, 220, 67, 45, 218 },
                            RefreshToken = "",
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "User",
                            Username = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(598),
                            Email = "pringle@example.com",
                            PasswordHash = new byte[] { 210, 67, 204, 231, 29, 74, 111, 142, 238, 93, 89, 134, 7, 9, 34, 28, 222, 240, 196, 135, 179, 249, 202, 37, 6, 118, 192, 100, 67, 128, 65, 176, 10, 128, 229, 1, 152, 101, 38, 137, 93, 137, 157, 49, 192, 57, 5, 89, 127, 40, 114, 117, 221, 107, 172, 92, 100, 83, 255, 52, 40, 150, 133, 125 },
                            PasswordSalt = new byte[] { 62, 118, 192, 184, 48, 81, 130, 208, 55, 108, 175, 82, 150, 31, 72, 234, 251, 250, 23, 70, 81, 44, 22, 107, 83, 23, 25, 118, 121, 141, 45, 103, 241, 233, 196, 242, 39, 86, 67, 148, 49, 196, 82, 201, 195, 174, 136, 50, 70, 221, 151, 28, 0, 236, 139, 6, 221, 172, 205, 189, 154, 116, 46, 116, 154, 12, 133, 219, 3, 151, 33, 112, 113, 60, 150, 37, 33, 86, 166, 28, 103, 96, 65, 208, 196, 157, 38, 226, 141, 82, 80, 82, 245, 94, 40, 112, 38, 91, 192, 39, 172, 163, 45, 49, 233, 95, 4, 87, 3, 111, 220, 109, 169, 5, 35, 215, 126, 211, 15, 137, 198, 98, 101, 48, 201, 44, 9, 11 },
                            RefreshToken = "",
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "User",
                            Username = "Pringleton"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2022, 7, 5, 21, 20, 54, 484, DateTimeKind.Utc).AddTicks(643),
                            Email = "john@dot.net",
                            PasswordHash = new byte[] { 37, 102, 175, 84, 137, 33, 30, 34, 140, 201, 196, 11, 57, 75, 81, 85, 132, 166, 43, 234, 25, 255, 202, 229, 252, 93, 73, 225, 51, 25, 206, 114, 17, 118, 77, 130, 64, 11, 228, 221, 143, 215, 35, 210, 141, 158, 94, 13, 99, 203, 174, 207, 235, 15, 127, 26, 16, 195, 203, 225, 74, 235, 172, 135 },
                            PasswordSalt = new byte[] { 8, 137, 60, 216, 149, 31, 103, 173, 21, 105, 62, 71, 109, 66, 208, 4, 101, 240, 253, 232, 201, 101, 164, 203, 64, 96, 78, 49, 89, 74, 179, 14, 110, 103, 4, 82, 122, 243, 151, 33, 17, 9, 209, 146, 9, 194, 225, 194, 81, 223, 200, 218, 107, 189, 16, 222, 147, 5, 154, 156, 127, 217, 157, 140, 87, 236, 167, 7, 36, 124, 226, 19, 74, 218, 118, 198, 162, 13, 137, 75, 188, 165, 210, 169, 82, 212, 193, 227, 91, 27, 250, 54, 36, 133, 31, 143, 165, 10, 57, 109, 208, 235, 14, 164, 235, 114, 83, 153, 95, 101, 186, 252, 191, 159, 42, 173, 160, 37, 35, 77, 22, 93, 4, 215, 84, 177, 163, 18 },
                            RefreshToken = "",
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "User",
                            Username = "John Dotnet"
                        });
                });

            modelBuilder.Entity("SharpScape.Api.Models.ForumPost", b =>
                {
                    b.HasOne("SharpScape.Api.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharpScape.Api.Models.ForumThread", "ForumThread")
                        .WithMany()
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("ForumThread");
                });

            modelBuilder.Entity("SharpScape.Api.Models.ForumThread", b =>
                {
                    b.HasOne("SharpScape.Api.Models.ForumCategory", "ForumCategory")
                        .WithMany("Threads")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharpScape.Api.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("ForumCategory");
                });

            modelBuilder.Entity("SharpScape.Api.Models.ForumCategory", b =>
                {
                    b.Navigation("Threads");
                });
#pragma warning restore 612, 618
        }
    }
}
