// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SharpScape.Api.Data;

#nullable disable

namespace SharpScape.Api.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    partial class SqliteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("SharpScape.Api.Models.ForumCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ForumCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Talk about sports, entertainment, music, movies, your favorite color, talk about enything.",
                            Name = "General Discussion"
                        },
                        new
                        {
                            Id = 2,
                            Description = "New to the community? Please stop by, say hi and tell us a bit about yourself.",
                            Name = "Introductions"
                        },
                        new
                        {
                            Id = 3,
                            Description = "This forum features announcements from the community staff. If there is a new post in this forum, please check it out.",
                            Name = "Announcements"
                        },
                        new
                        {
                            Id = 4,
                            Description = "This forum is for private, staff member only discussions, usually pertaining to the community itself.",
                            Name = "Staff Discussion"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Various versions have evolved over the years, sometimes by accident, sometimes on purpose passage of Lorem Ipsum (injected humour and the like).",
                            Name = "Lorem Ipsum is simply dummy text"
                        },
                        new
                        {
                            Id = 6,
                            Description = "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
                            Name = "There are many variations of passages"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
                            Name = "The standard chunk of Lorem Ipsum"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Internet tend to repeat predefined chunks as necessary, making this the.",
                            Name = "Lorem Ipsum, you need to be sure there"
                        });
                });

            modelBuilder.Entity("SharpScape.Api.Models.ForumPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("ThreadId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ThreadId");

                    b.ToTable("ForumPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(288),
                            ThreadId = 2
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(296),
                            ThreadId = 3
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(300),
                            ThreadId = 4
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(304),
                            ThreadId = 5
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(307),
                            ThreadId = 6
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(312),
                            ThreadId = 7
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(316),
                            ThreadId = 8
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(320),
                            ThreadId = 1
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(323),
                            ThreadId = 2
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(328),
                            ThreadId = 3
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(332),
                            ThreadId = 4
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(335),
                            ThreadId = 5
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(339),
                            ThreadId = 6
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(342),
                            ThreadId = 7
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(346),
                            ThreadId = 8
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(349),
                            ThreadId = 1
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(353),
                            ThreadId = 2
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(357),
                            ThreadId = 3
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(362),
                            ThreadId = 4
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(365),
                            ThreadId = 5
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(369),
                            ThreadId = 6
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(372),
                            ThreadId = 7
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(376),
                            ThreadId = 8
                        },
                        new
                        {
                            Id = 24,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(379),
                            ThreadId = 1
                        },
                        new
                        {
                            Id = 25,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(382),
                            ThreadId = 2
                        },
                        new
                        {
                            Id = 26,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(386),
                            ThreadId = 3
                        },
                        new
                        {
                            Id = 27,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(389),
                            ThreadId = 4
                        },
                        new
                        {
                            Id = 28,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(393),
                            ThreadId = 5
                        },
                        new
                        {
                            Id = 29,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(396),
                            ThreadId = 6
                        },
                        new
                        {
                            Id = 30,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(399),
                            ThreadId = 7
                        },
                        new
                        {
                            Id = 31,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(403),
                            ThreadId = 8
                        },
                        new
                        {
                            Id = 32,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(406),
                            ThreadId = 1
                        },
                        new
                        {
                            Id = 33,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(410),
                            ThreadId = 2
                        },
                        new
                        {
                            Id = 34,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(414),
                            ThreadId = 3
                        },
                        new
                        {
                            Id = 35,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(418),
                            ThreadId = 4
                        },
                        new
                        {
                            Id = 36,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(422),
                            ThreadId = 5
                        },
                        new
                        {
                            Id = 37,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(425),
                            ThreadId = 6
                        },
                        new
                        {
                            Id = 38,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(429),
                            ThreadId = 7
                        },
                        new
                        {
                            Id = 39,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(432),
                            ThreadId = 8
                        },
                        new
                        {
                            Id = 40,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(436),
                            ThreadId = 1
                        },
                        new
                        {
                            Id = 41,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(439),
                            ThreadId = 2
                        },
                        new
                        {
                            Id = 42,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(442),
                            ThreadId = 3
                        },
                        new
                        {
                            Id = 43,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(446),
                            ThreadId = 4
                        },
                        new
                        {
                            Id = 44,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(450),
                            ThreadId = 5
                        },
                        new
                        {
                            Id = 45,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(453),
                            ThreadId = 6
                        },
                        new
                        {
                            Id = 46,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(456),
                            ThreadId = 7
                        },
                        new
                        {
                            Id = 47,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(460),
                            ThreadId = 8
                        },
                        new
                        {
                            Id = 48,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(463),
                            ThreadId = 1
                        },
                        new
                        {
                            Id = 49,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(466),
                            ThreadId = 2
                        },
                        new
                        {
                            Id = 50,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(470),
                            ThreadId = 3
                        },
                        new
                        {
                            Id = 51,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(473),
                            ThreadId = 4
                        },
                        new
                        {
                            Id = 52,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(477),
                            ThreadId = 5
                        },
                        new
                        {
                            Id = 53,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(480),
                            ThreadId = 6
                        },
                        new
                        {
                            Id = 54,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(483),
                            ThreadId = 7
                        },
                        new
                        {
                            Id = 55,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(487),
                            ThreadId = 8
                        },
                        new
                        {
                            Id = 56,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(490),
                            ThreadId = 1
                        },
                        new
                        {
                            Id = 57,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(494),
                            ThreadId = 2
                        },
                        new
                        {
                            Id = 58,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(497),
                            ThreadId = 3
                        },
                        new
                        {
                            Id = 59,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(500),
                            ThreadId = 4
                        },
                        new
                        {
                            Id = 60,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(504),
                            ThreadId = 5
                        },
                        new
                        {
                            Id = 61,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(507),
                            ThreadId = 6
                        },
                        new
                        {
                            Id = 62,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(511),
                            ThreadId = 7
                        },
                        new
                        {
                            Id = 63,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(514),
                            ThreadId = 8
                        },
                        new
                        {
                            Id = 64,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 466, DateTimeKind.Utc).AddTicks(518),
                            ThreadId = 1
                        });
                });

            modelBuilder.Entity("SharpScape.Api.Models.ForumThread", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("Replies")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Views")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Votes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("ForumThreads");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
                            CategoryId = 1,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 465, DateTimeKind.Local).AddTicks(9821),
                            Replies = 0,
                            Title = "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 2,
                            Body = "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
                            CategoryId = 1,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 465, DateTimeKind.Local).AddTicks(9828),
                            Replies = 0,
                            Title = "qui est esse",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 3,
                            Body = "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
                            CategoryId = 1,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 465, DateTimeKind.Local).AddTicks(9833),
                            Replies = 0,
                            Title = "ea molestias quasi exercitationem repellat qui ipsa sit aut",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 4,
                            Body = "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
                            CategoryId = 1,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 465, DateTimeKind.Local).AddTicks(9839),
                            Replies = 0,
                            Title = "eum et est occaecati",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 5,
                            Body = "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
                            CategoryId = 1,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 465, DateTimeKind.Local).AddTicks(9844),
                            Replies = 0,
                            Title = "nesciunt quas odio",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 6,
                            Body = "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
                            CategoryId = 1,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 465, DateTimeKind.Local).AddTicks(9849),
                            Replies = 0,
                            Title = "dolorem eum magni eos aperiam quia",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 7,
                            Body = "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
                            CategoryId = 1,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 465, DateTimeKind.Local).AddTicks(9854),
                            Replies = 0,
                            Title = "magnam facilis autem",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 8,
                            Body = "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
                            CategoryId = 1,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 465, DateTimeKind.Local).AddTicks(9860),
                            Replies = 0,
                            Title = "dolorem dolore est ipsam",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 9,
                            Body = "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
                            CategoryId = 2,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 465, DateTimeKind.Local).AddTicks(9865),
                            Replies = 0,
                            Title = "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 10,
                            Body = "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
                            CategoryId = 2,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 465, DateTimeKind.Local).AddTicks(9870),
                            Replies = 0,
                            Title = "qui est esse",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 11,
                            Body = "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
                            CategoryId = 2,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 465, DateTimeKind.Local).AddTicks(9876),
                            Replies = 0,
                            Title = "ea molestias quasi exercitationem repellat qui ipsa sit aut",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 12,
                            Body = "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
                            CategoryId = 2,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 465, DateTimeKind.Local).AddTicks(9881),
                            Replies = 0,
                            Title = "eum et est occaecati",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 13,
                            Body = "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
                            CategoryId = 2,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 465, DateTimeKind.Local).AddTicks(9886),
                            Replies = 0,
                            Title = "nesciunt quas odio",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 14,
                            Body = "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
                            CategoryId = 2,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 465, DateTimeKind.Local).AddTicks(9891),
                            Replies = 0,
                            Title = "dolorem eum magni eos aperiam quia",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 15,
                            Body = "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
                            CategoryId = 2,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 465, DateTimeKind.Local).AddTicks(9897),
                            Replies = 0,
                            Title = "magnam facilis autem",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 16,
                            Body = "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
                            CategoryId = 2,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 465, DateTimeKind.Local).AddTicks(9902),
                            Replies = 0,
                            Title = "dolorem dolore est ipsam",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 17,
                            Body = "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
                            CategoryId = 3,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 465, DateTimeKind.Local).AddTicks(9908),
                            Replies = 0,
                            Title = "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 18,
                            Body = "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
                            CategoryId = 3,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 465, DateTimeKind.Local).AddTicks(9913),
                            Replies = 0,
                            Title = "qui est esse",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 19,
                            Body = "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
                            CategoryId = 3,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 465, DateTimeKind.Local).AddTicks(9919),
                            Replies = 0,
                            Title = "ea molestias quasi exercitationem repellat qui ipsa sit aut",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 20,
                            Body = "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
                            CategoryId = 3,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 465, DateTimeKind.Local).AddTicks(9924),
                            Replies = 0,
                            Title = "eum et est occaecati",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 21,
                            Body = "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
                            CategoryId = 3,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 465, DateTimeKind.Local).AddTicks(9929),
                            Replies = 0,
                            Title = "nesciunt quas odio",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 22,
                            Body = "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
                            CategoryId = 3,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 465, DateTimeKind.Local).AddTicks(9935),
                            Replies = 0,
                            Title = "dolorem eum magni eos aperiam quia",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 23,
                            Body = "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
                            CategoryId = 3,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 465, DateTimeKind.Local).AddTicks(9940),
                            Replies = 0,
                            Title = "magnam facilis autem",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 24,
                            Body = "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
                            CategoryId = 3,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 465, DateTimeKind.Local).AddTicks(9946),
                            Replies = 0,
                            Title = "dolorem dolore est ipsam",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 25,
                            Body = "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
                            CategoryId = 3,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 465, DateTimeKind.Local).AddTicks(9951),
                            Replies = 0,
                            Title = "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 26,
                            Body = "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
                            CategoryId = 3,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 465, DateTimeKind.Local).AddTicks(9956),
                            Replies = 0,
                            Title = "qui est esse",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 27,
                            Body = "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
                            CategoryId = 3,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 465, DateTimeKind.Local).AddTicks(9962),
                            Replies = 0,
                            Title = "ea molestias quasi exercitationem repellat qui ipsa sit aut",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 28,
                            Body = "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
                            CategoryId = 3,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 465, DateTimeKind.Local).AddTicks(9967),
                            Replies = 0,
                            Title = "eum et est occaecati",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 29,
                            Body = "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
                            CategoryId = 3,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 465, DateTimeKind.Local).AddTicks(9972),
                            Replies = 0,
                            Title = "nesciunt quas odio",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 30,
                            Body = "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
                            CategoryId = 3,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 465, DateTimeKind.Local).AddTicks(9977),
                            Replies = 0,
                            Title = "dolorem eum magni eos aperiam quia",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 31,
                            Body = "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
                            CategoryId = 3,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 465, DateTimeKind.Local).AddTicks(9983),
                            Replies = 0,
                            Title = "magnam facilis autem",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 32,
                            Body = "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
                            CategoryId = 3,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 465, DateTimeKind.Local).AddTicks(9989),
                            Replies = 0,
                            Title = "dolorem dolore est ipsam",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 33,
                            Body = "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
                            CategoryId = 5,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 465, DateTimeKind.Local).AddTicks(9995),
                            Replies = 0,
                            Title = "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 34,
                            Body = "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
                            CategoryId = 5,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 466, DateTimeKind.Local).AddTicks(1),
                            Replies = 0,
                            Title = "qui est esse",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 35,
                            Body = "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
                            CategoryId = 5,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 466, DateTimeKind.Local).AddTicks(7),
                            Replies = 0,
                            Title = "ea molestias quasi exercitationem repellat qui ipsa sit aut",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 36,
                            Body = "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
                            CategoryId = 5,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 466, DateTimeKind.Local).AddTicks(12),
                            Replies = 0,
                            Title = "eum et est occaecati",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 37,
                            Body = "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
                            CategoryId = 5,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 466, DateTimeKind.Local).AddTicks(17),
                            Replies = 0,
                            Title = "nesciunt quas odio",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 38,
                            Body = "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
                            CategoryId = 5,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 466, DateTimeKind.Local).AddTicks(23),
                            Replies = 0,
                            Title = "dolorem eum magni eos aperiam quia",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 39,
                            Body = "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
                            CategoryId = 5,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 466, DateTimeKind.Local).AddTicks(28),
                            Replies = 0,
                            Title = "magnam facilis autem",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 40,
                            Body = "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
                            CategoryId = 5,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 466, DateTimeKind.Local).AddTicks(33),
                            Replies = 0,
                            Title = "dolorem dolore est ipsam",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 41,
                            Body = "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
                            CategoryId = 6,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 466, DateTimeKind.Local).AddTicks(38),
                            Replies = 0,
                            Title = "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 42,
                            Body = "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
                            CategoryId = 6,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 466, DateTimeKind.Local).AddTicks(44),
                            Replies = 0,
                            Title = "qui est esse",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 43,
                            Body = "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
                            CategoryId = 6,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 466, DateTimeKind.Local).AddTicks(49),
                            Replies = 0,
                            Title = "ea molestias quasi exercitationem repellat qui ipsa sit aut",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 44,
                            Body = "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
                            CategoryId = 6,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 466, DateTimeKind.Local).AddTicks(54),
                            Replies = 0,
                            Title = "eum et est occaecati",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 45,
                            Body = "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
                            CategoryId = 6,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 466, DateTimeKind.Local).AddTicks(60),
                            Replies = 0,
                            Title = "nesciunt quas odio",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 46,
                            Body = "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
                            CategoryId = 6,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 466, DateTimeKind.Local).AddTicks(65),
                            Replies = 0,
                            Title = "dolorem eum magni eos aperiam quia",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 47,
                            Body = "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
                            CategoryId = 6,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 466, DateTimeKind.Local).AddTicks(71),
                            Replies = 0,
                            Title = "magnam facilis autem",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 48,
                            Body = "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
                            CategoryId = 6,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 466, DateTimeKind.Local).AddTicks(77),
                            Replies = 0,
                            Title = "dolorem dolore est ipsam",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 49,
                            Body = "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
                            CategoryId = 7,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 466, DateTimeKind.Local).AddTicks(82),
                            Replies = 0,
                            Title = "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 50,
                            Body = "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
                            CategoryId = 7,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 466, DateTimeKind.Local).AddTicks(87),
                            Replies = 0,
                            Title = "qui est esse",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 51,
                            Body = "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
                            CategoryId = 7,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 466, DateTimeKind.Local).AddTicks(93),
                            Replies = 0,
                            Title = "ea molestias quasi exercitationem repellat qui ipsa sit aut",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 52,
                            Body = "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
                            CategoryId = 7,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 466, DateTimeKind.Local).AddTicks(143),
                            Replies = 0,
                            Title = "eum et est occaecati",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 53,
                            Body = "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
                            CategoryId = 7,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 466, DateTimeKind.Local).AddTicks(149),
                            Replies = 0,
                            Title = "nesciunt quas odio",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 54,
                            Body = "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
                            CategoryId = 7,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 466, DateTimeKind.Local).AddTicks(154),
                            Replies = 0,
                            Title = "dolorem eum magni eos aperiam quia",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 55,
                            Body = "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
                            CategoryId = 7,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 466, DateTimeKind.Local).AddTicks(160),
                            Replies = 0,
                            Title = "magnam facilis autem",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 56,
                            Body = "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
                            CategoryId = 7,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 466, DateTimeKind.Local).AddTicks(165),
                            Replies = 0,
                            Title = "dolorem dolore est ipsam",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 57,
                            Body = "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
                            CategoryId = 8,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 466, DateTimeKind.Local).AddTicks(204),
                            Replies = 0,
                            Title = "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 58,
                            Body = "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
                            CategoryId = 8,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 466, DateTimeKind.Local).AddTicks(210),
                            Replies = 0,
                            Title = "qui est esse",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 59,
                            Body = "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
                            CategoryId = 8,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 466, DateTimeKind.Local).AddTicks(215),
                            Replies = 0,
                            Title = "ea molestias quasi exercitationem repellat qui ipsa sit aut",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 60,
                            Body = "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
                            CategoryId = 8,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 466, DateTimeKind.Local).AddTicks(221),
                            Replies = 0,
                            Title = "eum et est occaecati",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 61,
                            Body = "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
                            CategoryId = 8,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 466, DateTimeKind.Local).AddTicks(226),
                            Replies = 0,
                            Title = "nesciunt quas odio",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 62,
                            Body = "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
                            CategoryId = 8,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 466, DateTimeKind.Local).AddTicks(231),
                            Replies = 0,
                            Title = "dolorem eum magni eos aperiam quia",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 63,
                            Body = "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
                            CategoryId = 8,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 466, DateTimeKind.Local).AddTicks(236),
                            Replies = 0,
                            Title = "magnam facilis autem",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 64,
                            Body = "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
                            CategoryId = 8,
                            Created = new DateTime(2022, 6, 28, 11, 22, 32, 466, DateTimeKind.Local).AddTicks(242),
                            Replies = 0,
                            Title = "dolorem dolore est ipsam",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        });
                });

            modelBuilder.Entity("SharpScape.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 465, DateTimeKind.Utc).AddTicks(9167),
                            Email = "admin@sharpscape.net",
                            PasswordHash = new byte[] { 134, 206, 227, 249, 140, 186, 223, 76, 66, 160, 104, 238, 121, 42, 127, 183, 245, 79, 59, 247, 238, 204, 24, 6, 45, 27, 101, 216, 47, 190, 161, 168, 172, 234, 130, 166, 227, 45, 122, 59, 142, 230, 176, 160, 80, 101, 3, 65, 199, 12, 76, 126, 125, 220, 244, 101, 105, 141, 73, 224, 177, 115, 172, 167 },
                            PasswordSalt = new byte[] { 48, 64, 134, 47, 89, 215, 123, 84, 101, 126, 124, 66, 88, 135, 26, 58, 218, 190, 93, 246, 230, 248, 11, 104, 116, 11, 195, 211, 250, 208, 112, 193, 18, 18, 5, 250, 118, 233, 255, 177, 80, 131, 152, 131, 33, 190, 20, 131, 243, 48, 245, 25, 38, 36, 146, 151, 145, 213, 42, 103, 125, 4, 44, 19, 222, 180, 74, 69, 150, 16, 182, 39, 142, 47, 169, 191, 111, 162, 201, 214, 246, 96, 12, 230, 231, 70, 133, 186, 185, 210, 219, 1, 106, 142, 109, 82, 124, 132, 210, 96, 69, 45, 43, 132, 213, 179, 139, 122, 67, 12, 164, 221, 169, 225, 125, 86, 68, 237, 163, 34, 184, 247, 155, 179, 245, 132, 39, 177 },
                            Role = "User",
                            Username = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 465, DateTimeKind.Utc).AddTicks(9516),
                            Email = "pringle@example.com",
                            PasswordHash = new byte[] { 83, 114, 10, 254, 115, 85, 136, 152, 5, 150, 101, 5, 55, 18, 223, 122, 106, 241, 67, 14, 183, 59, 18, 170, 150, 115, 53, 126, 226, 55, 36, 73, 151, 220, 75, 112, 145, 160, 225, 1, 99, 125, 115, 232, 25, 213, 101, 230, 188, 110, 150, 178, 51, 81, 158, 191, 141, 227, 138, 197, 197, 140, 213, 61 },
                            PasswordSalt = new byte[] { 125, 10, 96, 77, 228, 213, 133, 251, 6, 230, 130, 153, 109, 201, 234, 65, 255, 25, 233, 69, 91, 51, 226, 198, 98, 149, 120, 35, 11, 31, 165, 154, 62, 59, 187, 179, 198, 140, 99, 157, 175, 173, 148, 98, 156, 177, 95, 194, 191, 72, 67, 172, 181, 200, 62, 153, 50, 228, 220, 173, 170, 237, 17, 121, 250, 129, 74, 6, 133, 116, 155, 88, 62, 103, 166, 243, 165, 68, 29, 59, 20, 64, 88, 174, 147, 181, 206, 81, 246, 60, 113, 38, 195, 165, 1, 26, 0, 71, 127, 205, 102, 59, 133, 157, 52, 235, 81, 208, 95, 153, 177, 87, 187, 113, 192, 35, 229, 150, 227, 183, 55, 170, 43, 162, 211, 176, 80, 156 },
                            Role = "User",
                            Username = "Pringleton"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2022, 6, 28, 15, 22, 32, 465, DateTimeKind.Utc).AddTicks(9565),
                            Email = "john@dot.net",
                            PasswordHash = new byte[] { 198, 190, 61, 102, 86, 182, 198, 217, 204, 240, 66, 71, 204, 111, 234, 60, 43, 66, 35, 208, 184, 24, 206, 48, 132, 59, 38, 191, 154, 7, 240, 167, 204, 41, 137, 101, 249, 158, 144, 212, 61, 93, 74, 137, 84, 45, 60, 225, 51, 70, 114, 242, 182, 109, 203, 216, 161, 246, 34, 31, 208, 220, 54, 119 },
                            PasswordSalt = new byte[] { 139, 65, 199, 107, 190, 227, 75, 209, 218, 217, 24, 104, 39, 52, 186, 79, 138, 153, 187, 10, 43, 156, 199, 93, 65, 219, 86, 83, 243, 118, 135, 199, 166, 6, 117, 249, 204, 1, 97, 86, 201, 26, 88, 1, 196, 179, 226, 138, 74, 180, 238, 133, 141, 35, 21, 61, 9, 38, 234, 52, 141, 255, 156, 164, 34, 254, 9, 157, 237, 198, 180, 96, 253, 235, 40, 19, 59, 103, 49, 162, 138, 224, 62, 102, 41, 19, 201, 214, 63, 66, 213, 34, 102, 55, 239, 101, 214, 173, 172, 103, 247, 79, 139, 180, 72, 78, 164, 147, 135, 60, 193, 213, 47, 111, 217, 57, 14, 111, 223, 130, 135, 7, 140, 66, 113, 56, 227, 201 },
                            Role = "User",
                            Username = "John Dotnet"
                        });
                });

            modelBuilder.Entity("SharpScape.Api.Models.ForumPost", b =>
                {
                    b.HasOne("SharpScape.Api.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharpScape.Api.Models.ForumThread", "ForumThread")
                        .WithMany()
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("ForumThread");
                });

            modelBuilder.Entity("SharpScape.Api.Models.ForumThread", b =>
                {
                    b.HasOne("SharpScape.Api.Models.ForumCategory", "ForumCategory")
                        .WithMany("Threads")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharpScape.Api.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("ForumCategory");
                });

            modelBuilder.Entity("SharpScape.Api.Models.ForumCategory", b =>
                {
                    b.Navigation("Threads");
                });
#pragma warning restore 612, 618
        }
    }
}
