// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SharpScape.Api.Data;

#nullable disable

namespace SharpScape.Api.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    partial class SqliteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("SharpScape.Api.Models.ForumCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ForumCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Talk about sports, entertainment, music, movies, your favorite color, talk about enything.",
                            Name = "General Discussion"
                        },
                        new
                        {
                            Id = 2,
                            Description = "New to the community? Please stop by, say hi and tell us a bit about yourself.",
                            Name = "Introductions"
                        },
                        new
                        {
                            Id = 3,
                            Description = "This forum features announcements from the community staff. If there is a new post in this forum, please check it out.",
                            Name = "Announcements"
                        },
                        new
                        {
                            Id = 4,
                            Description = "This forum is for private, staff member only discussions, usually pertaining to the community itself.",
                            Name = "Staff Discussion"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Various versions have evolved over the years, sometimes by accident, sometimes on purpose passage of Lorem Ipsum (injected humour and the like).",
                            Name = "Lorem Ipsum is simply dummy text"
                        },
                        new
                        {
                            Id = 6,
                            Description = "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the.",
                            Name = "There are many variations of passages"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
                            Name = "The standard chunk of Lorem Ipsum"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Internet tend to repeat predefined chunks as necessary, making this the.",
                            Name = "Lorem Ipsum, you need to be sure there"
                        });
                });

            modelBuilder.Entity("SharpScape.Api.Models.ForumPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("ThreadId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ThreadId");

                    b.ToTable("ForumPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3575),
                            ThreadId = 2
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3585),
                            ThreadId = 3
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3589),
                            ThreadId = 4
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3594),
                            ThreadId = 5
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3598),
                            ThreadId = 6
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3603),
                            ThreadId = 7
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3608),
                            ThreadId = 8
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3612),
                            ThreadId = 1
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3616),
                            ThreadId = 2
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3622),
                            ThreadId = 3
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3626),
                            ThreadId = 4
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3630),
                            ThreadId = 5
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3635),
                            ThreadId = 6
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3639),
                            ThreadId = 7
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3643),
                            ThreadId = 8
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3647),
                            ThreadId = 1
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3651),
                            ThreadId = 2
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3657),
                            ThreadId = 3
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3661),
                            ThreadId = 4
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3665),
                            ThreadId = 5
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3732),
                            ThreadId = 6
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3737),
                            ThreadId = 7
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3742),
                            ThreadId = 8
                        },
                        new
                        {
                            Id = 24,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3746),
                            ThreadId = 1
                        },
                        new
                        {
                            Id = 25,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3750),
                            ThreadId = 2
                        },
                        new
                        {
                            Id = 26,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3754),
                            ThreadId = 3
                        },
                        new
                        {
                            Id = 27,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3759),
                            ThreadId = 4
                        },
                        new
                        {
                            Id = 28,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3763),
                            ThreadId = 5
                        },
                        new
                        {
                            Id = 29,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3767),
                            ThreadId = 6
                        },
                        new
                        {
                            Id = 30,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3771),
                            ThreadId = 7
                        },
                        new
                        {
                            Id = 31,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3776),
                            ThreadId = 8
                        },
                        new
                        {
                            Id = 32,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3780),
                            ThreadId = 1
                        },
                        new
                        {
                            Id = 33,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3784),
                            ThreadId = 2
                        },
                        new
                        {
                            Id = 34,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3790),
                            ThreadId = 3
                        },
                        new
                        {
                            Id = 35,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3795),
                            ThreadId = 4
                        },
                        new
                        {
                            Id = 36,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3799),
                            ThreadId = 5
                        },
                        new
                        {
                            Id = 37,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3803),
                            ThreadId = 6
                        },
                        new
                        {
                            Id = 38,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3807),
                            ThreadId = 7
                        },
                        new
                        {
                            Id = 39,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3812),
                            ThreadId = 8
                        },
                        new
                        {
                            Id = 40,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3816),
                            ThreadId = 1
                        },
                        new
                        {
                            Id = 41,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3820),
                            ThreadId = 2
                        },
                        new
                        {
                            Id = 42,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3824),
                            ThreadId = 3
                        },
                        new
                        {
                            Id = 43,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3828),
                            ThreadId = 4
                        },
                        new
                        {
                            Id = 44,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3833),
                            ThreadId = 5
                        },
                        new
                        {
                            Id = 45,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3837),
                            ThreadId = 6
                        },
                        new
                        {
                            Id = 46,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3841),
                            ThreadId = 7
                        },
                        new
                        {
                            Id = 47,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3845),
                            ThreadId = 8
                        },
                        new
                        {
                            Id = 48,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3850),
                            ThreadId = 1
                        },
                        new
                        {
                            Id = 49,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3854),
                            ThreadId = 2
                        },
                        new
                        {
                            Id = 50,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3858),
                            ThreadId = 3
                        },
                        new
                        {
                            Id = 51,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3862),
                            ThreadId = 4
                        },
                        new
                        {
                            Id = 52,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3867),
                            ThreadId = 5
                        },
                        new
                        {
                            Id = 53,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3871),
                            ThreadId = 6
                        },
                        new
                        {
                            Id = 54,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3875),
                            ThreadId = 7
                        },
                        new
                        {
                            Id = 55,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3879),
                            ThreadId = 8
                        },
                        new
                        {
                            Id = 56,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3884),
                            ThreadId = 1
                        },
                        new
                        {
                            Id = 57,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3888),
                            ThreadId = 2
                        },
                        new
                        {
                            Id = 58,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3892),
                            ThreadId = 3
                        },
                        new
                        {
                            Id = 59,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3896),
                            ThreadId = 4
                        },
                        new
                        {
                            Id = 60,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3901),
                            ThreadId = 5
                        },
                        new
                        {
                            Id = 61,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3905),
                            ThreadId = 6
                        },
                        new
                        {
                            Id = 62,
                            AuthorId = 3,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3909),
                            ThreadId = 7
                        },
                        new
                        {
                            Id = 63,
                            AuthorId = 1,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3913),
                            ThreadId = 8
                        },
                        new
                        {
                            Id = 64,
                            AuthorId = 2,
                            Body = "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et",
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(3917),
                            ThreadId = 1
                        });
                });

            modelBuilder.Entity("SharpScape.Api.Models.ForumThread", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("Replies")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Views")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Votes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("ForumThreads");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
                            CategoryId = 1,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3052),
                            Replies = 0,
                            Title = "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 2,
                            Body = "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
                            CategoryId = 1,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3062),
                            Replies = 0,
                            Title = "qui est esse",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 3,
                            Body = "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
                            CategoryId = 1,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3118),
                            Replies = 0,
                            Title = "ea molestias quasi exercitationem repellat qui ipsa sit aut",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 4,
                            Body = "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
                            CategoryId = 1,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3125),
                            Replies = 0,
                            Title = "eum et est occaecati",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 5,
                            Body = "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
                            CategoryId = 1,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3132),
                            Replies = 0,
                            Title = "nesciunt quas odio",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 6,
                            Body = "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
                            CategoryId = 1,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3138),
                            Replies = 0,
                            Title = "dolorem eum magni eos aperiam quia",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 7,
                            Body = "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
                            CategoryId = 1,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3145),
                            Replies = 0,
                            Title = "magnam facilis autem",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 8,
                            Body = "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
                            CategoryId = 1,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3152),
                            Replies = 0,
                            Title = "dolorem dolore est ipsam",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 9,
                            Body = "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
                            CategoryId = 2,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3159),
                            Replies = 0,
                            Title = "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 10,
                            Body = "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
                            CategoryId = 2,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3165),
                            Replies = 0,
                            Title = "qui est esse",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 11,
                            Body = "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
                            CategoryId = 2,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3172),
                            Replies = 0,
                            Title = "ea molestias quasi exercitationem repellat qui ipsa sit aut",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 12,
                            Body = "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
                            CategoryId = 2,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3179),
                            Replies = 0,
                            Title = "eum et est occaecati",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 13,
                            Body = "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
                            CategoryId = 2,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3185),
                            Replies = 0,
                            Title = "nesciunt quas odio",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 14,
                            Body = "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
                            CategoryId = 2,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3192),
                            Replies = 0,
                            Title = "dolorem eum magni eos aperiam quia",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 15,
                            Body = "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
                            CategoryId = 2,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3199),
                            Replies = 0,
                            Title = "magnam facilis autem",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 16,
                            Body = "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
                            CategoryId = 2,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3206),
                            Replies = 0,
                            Title = "dolorem dolore est ipsam",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 17,
                            Body = "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
                            CategoryId = 3,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3212),
                            Replies = 0,
                            Title = "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 18,
                            Body = "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
                            CategoryId = 3,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3219),
                            Replies = 0,
                            Title = "qui est esse",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 19,
                            Body = "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
                            CategoryId = 3,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3226),
                            Replies = 0,
                            Title = "ea molestias quasi exercitationem repellat qui ipsa sit aut",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 20,
                            Body = "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
                            CategoryId = 3,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3232),
                            Replies = 0,
                            Title = "eum et est occaecati",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 21,
                            Body = "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
                            CategoryId = 3,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3239),
                            Replies = 0,
                            Title = "nesciunt quas odio",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 22,
                            Body = "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
                            CategoryId = 3,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3245),
                            Replies = 0,
                            Title = "dolorem eum magni eos aperiam quia",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 23,
                            Body = "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
                            CategoryId = 3,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3252),
                            Replies = 0,
                            Title = "magnam facilis autem",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 24,
                            Body = "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
                            CategoryId = 3,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3259),
                            Replies = 0,
                            Title = "dolorem dolore est ipsam",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 25,
                            Body = "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
                            CategoryId = 3,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3265),
                            Replies = 0,
                            Title = "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 26,
                            Body = "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
                            CategoryId = 3,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3272),
                            Replies = 0,
                            Title = "qui est esse",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 27,
                            Body = "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
                            CategoryId = 3,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3279),
                            Replies = 0,
                            Title = "ea molestias quasi exercitationem repellat qui ipsa sit aut",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 28,
                            Body = "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
                            CategoryId = 3,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3285),
                            Replies = 0,
                            Title = "eum et est occaecati",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 29,
                            Body = "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
                            CategoryId = 3,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3292),
                            Replies = 0,
                            Title = "nesciunt quas odio",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 30,
                            Body = "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
                            CategoryId = 3,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3299),
                            Replies = 0,
                            Title = "dolorem eum magni eos aperiam quia",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 31,
                            Body = "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
                            CategoryId = 3,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3306),
                            Replies = 0,
                            Title = "magnam facilis autem",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 32,
                            Body = "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
                            CategoryId = 3,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3312),
                            Replies = 0,
                            Title = "dolorem dolore est ipsam",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 33,
                            Body = "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
                            CategoryId = 5,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3319),
                            Replies = 0,
                            Title = "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 34,
                            Body = "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
                            CategoryId = 5,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3326),
                            Replies = 0,
                            Title = "qui est esse",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 35,
                            Body = "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
                            CategoryId = 5,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3332),
                            Replies = 0,
                            Title = "ea molestias quasi exercitationem repellat qui ipsa sit aut",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 36,
                            Body = "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
                            CategoryId = 5,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3339),
                            Replies = 0,
                            Title = "eum et est occaecati",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 37,
                            Body = "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
                            CategoryId = 5,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3345),
                            Replies = 0,
                            Title = "nesciunt quas odio",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 38,
                            Body = "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
                            CategoryId = 5,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3352),
                            Replies = 0,
                            Title = "dolorem eum magni eos aperiam quia",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 39,
                            Body = "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
                            CategoryId = 5,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3359),
                            Replies = 0,
                            Title = "magnam facilis autem",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 40,
                            Body = "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
                            CategoryId = 5,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3366),
                            Replies = 0,
                            Title = "dolorem dolore est ipsam",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 41,
                            Body = "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
                            CategoryId = 6,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3373),
                            Replies = 0,
                            Title = "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 42,
                            Body = "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
                            CategoryId = 6,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3380),
                            Replies = 0,
                            Title = "qui est esse",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 43,
                            Body = "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
                            CategoryId = 6,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3386),
                            Replies = 0,
                            Title = "ea molestias quasi exercitationem repellat qui ipsa sit aut",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 44,
                            Body = "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
                            CategoryId = 6,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3393),
                            Replies = 0,
                            Title = "eum et est occaecati",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 45,
                            Body = "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
                            CategoryId = 6,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3399),
                            Replies = 0,
                            Title = "nesciunt quas odio",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 46,
                            Body = "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
                            CategoryId = 6,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3406),
                            Replies = 0,
                            Title = "dolorem eum magni eos aperiam quia",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 47,
                            Body = "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
                            CategoryId = 6,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3413),
                            Replies = 0,
                            Title = "magnam facilis autem",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 48,
                            Body = "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
                            CategoryId = 6,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3419),
                            Replies = 0,
                            Title = "dolorem dolore est ipsam",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 49,
                            Body = "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
                            CategoryId = 7,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3426),
                            Replies = 0,
                            Title = "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 50,
                            Body = "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
                            CategoryId = 7,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3432),
                            Replies = 0,
                            Title = "qui est esse",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 51,
                            Body = "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
                            CategoryId = 7,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3439),
                            Replies = 0,
                            Title = "ea molestias quasi exercitationem repellat qui ipsa sit aut",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 52,
                            Body = "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
                            CategoryId = 7,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3446),
                            Replies = 0,
                            Title = "eum et est occaecati",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 53,
                            Body = "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
                            CategoryId = 7,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3452),
                            Replies = 0,
                            Title = "nesciunt quas odio",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 54,
                            Body = "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
                            CategoryId = 7,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3459),
                            Replies = 0,
                            Title = "dolorem eum magni eos aperiam quia",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 55,
                            Body = "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
                            CategoryId = 7,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3466),
                            Replies = 0,
                            Title = "magnam facilis autem",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 56,
                            Body = "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
                            CategoryId = 7,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3472),
                            Replies = 0,
                            Title = "dolorem dolore est ipsam",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 57,
                            Body = "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
                            CategoryId = 8,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3479),
                            Replies = 0,
                            Title = "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 58,
                            Body = "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
                            CategoryId = 8,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3485),
                            Replies = 0,
                            Title = "qui est esse",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 59,
                            Body = "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
                            CategoryId = 8,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3492),
                            Replies = 0,
                            Title = "ea molestias quasi exercitationem repellat qui ipsa sit aut",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 60,
                            Body = "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
                            CategoryId = 8,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3499),
                            Replies = 0,
                            Title = "eum et est occaecati",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 61,
                            Body = "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
                            CategoryId = 8,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3505),
                            Replies = 0,
                            Title = "nesciunt quas odio",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 62,
                            Body = "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
                            CategoryId = 8,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3512),
                            Replies = 0,
                            Title = "dolorem eum magni eos aperiam quia",
                            UserId = 1,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 63,
                            Body = "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
                            CategoryId = 8,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3519),
                            Replies = 0,
                            Title = "magnam facilis autem",
                            UserId = 3,
                            Views = 0,
                            Votes = 0
                        },
                        new
                        {
                            Id = 64,
                            Body = "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
                            CategoryId = 8,
                            Created = new DateTime(2022, 6, 23, 20, 57, 39, 967, DateTimeKind.Local).AddTicks(3525),
                            Replies = 0,
                            Title = "dolorem dolore est ipsam",
                            UserId = 2,
                            Views = 0,
                            Votes = 0
                        });
                });

            modelBuilder.Entity("SharpScape.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(2422),
                            Email = "admin@sharpscape.net",
                            PasswordHash = new byte[] { 54, 145, 59, 40, 237, 177, 17, 41, 177, 248, 144, 74, 6, 250, 168, 105, 254, 183, 95, 85, 208, 140, 75, 2, 28, 192, 223, 244, 156, 249, 242, 201, 78, 143, 121, 31, 101, 79, 47, 0, 162, 185, 113, 110, 235, 40, 17, 245, 96, 227, 52, 48, 117, 159, 8, 43, 27, 189, 25, 44, 0, 78, 127, 95 },
                            PasswordSalt = new byte[] { 121, 237, 87, 119, 185, 38, 42, 167, 104, 152, 116, 139, 117, 176, 199, 31, 4, 141, 14, 170, 140, 7, 211, 66, 134, 208, 13, 58, 224, 179, 234, 125, 245, 246, 46, 178, 62, 171, 7, 91, 99, 212, 29, 74, 12, 80, 246, 151, 109, 95, 172, 98, 1, 105, 172, 75, 142, 153, 196, 197, 211, 181, 9, 191, 83, 49, 136, 166, 166, 223, 200, 9, 228, 236, 34, 129, 217, 223, 234, 231, 247, 230, 237, 213, 224, 26, 94, 90, 151, 198, 169, 106, 93, 248, 232, 124, 154, 239, 111, 72, 240, 146, 169, 87, 68, 4, 93, 240, 108, 27, 100, 107, 60, 165, 149, 232, 37, 53, 112, 198, 98, 121, 145, 195, 133, 10, 39, 214 },
                            Role = "User",
                            Username = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(2725),
                            Email = "pringle@example.com",
                            PasswordHash = new byte[] { 112, 170, 8, 129, 67, 68, 246, 32, 188, 52, 79, 12, 106, 173, 177, 225, 42, 40, 17, 9, 165, 20, 27, 161, 198, 121, 61, 231, 177, 213, 232, 38, 72, 35, 75, 58, 255, 244, 125, 202, 191, 58, 25, 57, 155, 116, 64, 53, 107, 246, 240, 118, 194, 143, 183, 209, 90, 205, 208, 136, 58, 43, 169, 48 },
                            PasswordSalt = new byte[] { 171, 164, 89, 221, 75, 50, 13, 217, 87, 60, 154, 99, 70, 98, 177, 19, 196, 160, 234, 81, 184, 138, 77, 38, 66, 69, 38, 152, 169, 243, 44, 107, 58, 40, 150, 226, 144, 104, 64, 50, 30, 84, 113, 177, 49, 255, 188, 47, 227, 71, 30, 44, 163, 159, 18, 138, 56, 156, 23, 110, 119, 11, 68, 64, 92, 17, 175, 94, 6, 215, 13, 88, 123, 116, 161, 222, 214, 132, 21, 31, 190, 136, 4, 175, 87, 220, 60, 84, 241, 12, 127, 82, 115, 225, 145, 92, 206, 24, 231, 214, 144, 118, 50, 246, 120, 198, 153, 188, 138, 163, 147, 8, 115, 199, 19, 128, 134, 13, 131, 177, 222, 255, 176, 74, 67, 83, 143, 99 },
                            Role = "User",
                            Username = "Pringleton"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2022, 6, 24, 3, 57, 39, 967, DateTimeKind.Utc).AddTicks(2770),
                            Email = "john@dot.net",
                            PasswordHash = new byte[] { 126, 136, 189, 81, 224, 105, 122, 181, 45, 179, 33, 68, 108, 130, 86, 68, 154, 239, 253, 122, 46, 112, 111, 248, 142, 241, 2, 57, 59, 255, 18, 66, 177, 205, 8, 218, 147, 51, 32, 8, 132, 106, 108, 60, 195, 158, 169, 210, 13, 163, 42, 3, 60, 115, 130, 249, 38, 64, 233, 248, 86, 225, 13, 39 },
                            PasswordSalt = new byte[] { 102, 9, 221, 160, 95, 225, 90, 171, 189, 15, 215, 43, 65, 131, 117, 204, 190, 140, 254, 105, 2, 203, 54, 245, 55, 158, 43, 62, 220, 61, 117, 156, 243, 25, 198, 109, 35, 11, 86, 135, 11, 24, 6, 246, 8, 11, 163, 147, 45, 236, 6, 202, 105, 88, 231, 44, 165, 244, 142, 177, 95, 184, 237, 26, 104, 176, 209, 215, 218, 247, 140, 12, 246, 192, 8, 121, 238, 131, 23, 250, 134, 138, 59, 107, 92, 216, 215, 61, 145, 83, 129, 56, 189, 250, 34, 54, 46, 27, 113, 185, 216, 240, 183, 87, 28, 209, 72, 11, 88, 152, 11, 107, 178, 106, 203, 16, 251, 210, 246, 253, 174, 238, 204, 252, 27, 251, 106, 18 },
                            Role = "User",
                            Username = "John Dotnet"
                        });
                });

            modelBuilder.Entity("SharpScape.Api.Models.ForumPost", b =>
                {
                    b.HasOne("SharpScape.Api.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharpScape.Api.Models.ForumThread", "ForumThread")
                        .WithMany()
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("ForumThread");
                });

            modelBuilder.Entity("SharpScape.Api.Models.ForumThread", b =>
                {
                    b.HasOne("SharpScape.Api.Models.ForumCategory", "ForumCategory")
                        .WithMany("Threads")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharpScape.Api.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("ForumCategory");
                });

            modelBuilder.Entity("SharpScape.Api.Models.ForumCategory", b =>
                {
                    b.Navigation("Threads");
                });
#pragma warning restore 612, 618
        }
    }
}
